[package]
name = "Grafi_json"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.23"
crossterm = "0.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.3.1"
ndarray = "0.16.1"
linregress = "0.5.4"
lazy_static = "1.4.0"